apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: frantic-silkworm-nodejs 
  janus-idp.io/tekton: frantic-silkworm-nodejs
  backstage.io/kubernetes-id: frantic-silkworm-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: frantic-silkworm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  