apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: frantic-silkworm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frantic-silkworm-nodejs 
  name: frantic-silkworm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: frantic-silkworm-nodejs 
